name: 'main'

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build LaTeX document
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add py3-pygments
          make

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: bsc-thesis
        path: 215514_rafal_kolucki_inz.pdf
